name: publish

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write # Allows this job to create releases

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: 'pnpm'

      - name: Install deps and build
        run: |
          pnpm install
          pnpm build

      - name: Publish to npmjs.com
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Get package version
      #   run: echo "version=v$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     draft: true
      #     tag_name: ${{ env.version }}

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Release
        run: npx changelogithub --draft # or changelogithub@0.12 if ensure the stable result
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
